export { default as Loader } from "./Loader";
export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Ratings } from "./Ratings";
export { default as PageHead } from "./PageHead";
export { default as Navigation } from "./Navigation";
export { default as CustomModal } from "./CustomModal";
export { default as ThemeSwitcher } from "./ThemeToggle";
export { default as CoursePlayer } from "./CoursePlayer";
