export * from "./faq";
export * from "./auth";
export * from "./home";
export * from "./about";
export * from "./admin";
export * from "./common";
export * from "./course";
export * from "./profile";
export * from "./privacy";
